module.exports = {
  rules: {
    "yoda": ["error", "never", { exceptRange: true }],
    "wrap-iife": ["error", "inside"],
    "vars-on-top": "error",
    "require-unicode-regexp": "error",
    "require-await": "error",
    "radix": "error",
    "prefer-regex-literals": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-named-capture-group": "error",
    "no-with": "error",
    "no-warning-comments": "error",
    "no-void": "error",
    "no-useless-return": "error",
    "no-useless-escape": "error",
    "no-useless-concat": "error",
    "no-useless-catch": "error",
    "no-useless-call": "error",
    "no-unused-labels": "error",
    "no-unused-expressions": "error",
    "no-unmodified-loop-condition": "error",
    "no-throw-literal": "error",
    "no-sequences": "error",
    "no-self-compare": "error",
    "no-self-assign": "error",
    "no-script-url": "error",
    "no-return-await": "error",
    "no-return-assign": "error",
    "no-redeclare": "error",
    "no-proto": "error",
    "no-param-reassign": "error",
    "no-octal-escape": "error",
    "no-octal": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-new-wrappers": "error",
    "no-new-func": "error",
    "no-new": "error",
    "no-multi-str": "error",
    "no-multi-spaces": ["error", { ignoreEOLComments: true }],
    "no-magic-numbers": ["error", { ignore: [-1, 0, 1] }],
    "no-loop-func": "error",
    "no-lone-blocks": "error",
    "no-labels": "error",
    "no-iterator": "error",
    "no-invalid-this": "error",
    "no-implied-eval": "error",
    "no-implicit-globals": "error",
    "no-implicit-coercion": ["error", { allow: ["!!"]}],
    "no-global-assign": "error",
    "no-floating-decimal": "error",
    "no-fallthrough": "warn",
    "no-extra-label": "error",
    "no-extra-bind": "error",
    "no-extend-native": "error",
    "no-eval": "error",
    "no-eq-null": "error",
    "no-empty-pattern": "error",
    "no-empty-function": "error",
    "no-else-return": "error",
    "no-div-regex": "error",
    "no-constructor-return": "error",
    "no-case-declarations": "error",
    "no-caller": "error",
    "no-alert": "error",
    "max-classes-per-file": ["error", 1],
    "guard-for-in": "warn",
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "eqeqeq": "error",
    "dot-notation": "error",
    "dot-location": ["error", "property"],
    "default-case-last": "error",
    "default-case": "off",
    "curly": ["error", "multi-or-nest", "consistent"],
    "consistent-return": "error",
    "complexity": ["error", 10],
    "class-methods-use-this": "error",
    "block-scoped-var": "error",
    "array-callback-return": "error",
    "accessor-pairs": "off",
    "no-restricted-properties": "off"
  }
}