module.exports = {
  rules: {
    "yield-star-spacing": ["error", "before"],
    "template-curly-spacing": ["error", "never"],
    "symbol-description": "error",
    "sort-import": "off",
    "rest-spread-spacing": ["error", "never"],
    "require-yield": "error",
    "prefer-template": "error",
    "prefer-spread": "error",
    "prefer-rest-params": "error",
    "prefer-numeric-literals": "error",
    "prefer-destructuring": "error",
    "prefer-const": "error",
    "prefer-arrow-callback": "error",
    "object-shorthand": "off",
    "no-var": "error",
    "no-useless-rename": "error",
    "no-useless-constructor": "error",
    "no-useless-computed-key": "error",
    "no-this-before-super": "error",
    "no-new-symbol": "error",
    "no-duplicate-imports": "error",
    "no-dupe-class-members": "error",
    "no-const-assign": "error",
    "no-confusing-arrow": "off",
    "no-class-assign": "error",
    "generator-star-spacing": ["error", "before"],
    "constructor-super": "error",
    "arrow-spacing": ["error", { before: true, after: true }],
    "arrow-parens": ["error", "as-needed"],
    "arrow-body-style": ["error", "as-needed"],
  }
}