module.exports = {
  rules: {
    "wrap-regex": "off",
    "unicode-bom": ["error", "never"],
    "template-tag-spacing": ["error", "never"],
    "switch-colon-spacing": ["error", { before: false, after: true}],
    "spaced-comment": [
      "error",
      "always",
      {
        exceptions: ["*"],
        line: {
          markers: [ "#region", "#endregion", "/" ],
          exceptions: ["-"],
        },
        block: {
          balanced: true
        }
      }
    ],
    "space-unary-ops": "error",
    "space-infix-ops": "error",
    "space-in-parens": ["error", "never"],
    "space-before-function-paren": ["error", { anonymous: "always", named: "never", asyncArrow: "always" }],
    "space-before-blocks": ["error", "always"],
    "sort-vars": "off",
    "sort-keys": "off",
    "semi-style": ["error","last"],
    "semi-spacing": ["error", { before: false, after: true }],
    "semi": ["error", "never"],
    "quotes": ["error", "double", { avoidEscape: true }],
    "quote-props": ["error", "as-needed", { numbers: true }],
    "prefer-object-spread": "error",
    "prefer-exponentiation-operator": "error",
    "operator-linebreak": ["error", "before"],
    "operator-assignment": ["error", "always"],
    "one-var-declaration-per-line": ["error", "initializations"],
    "no-whitespace-before-property": "error",
    "no-unneeded-ternary": "error",
    "no-underscore-dangle": ["error", { allow: [ "_id" ]}],
    "no-trailing-spaces": "error",
    "no-ternary": "off",
    "no-tabs": "error",
    "no-plusplus": "off",
    "no-new-object": "error",
    "no-nested-ternary": "warn",
    "no-negated-condition": "error",
    "no-multiple-empty-lines": "error",
    "no-multi-assign": "error",
    "no-mixed-spaces-and-tabs": "error",
    "no-mixed-operators": "off",
    "no-lonely-if": "error",
    "no-inline-comments": "off",
    "no-continue": "off",
    "no-bitwise": "off",
    "no-array-constructor": "error",
    "new-parens": "error",
    "new-cap": "error",
    "max-statements-per-line": ["error", { max: 1 }],
    "max-len": ["error", {
      code: 80,
      ignoreTrailingComments: true,
      ignoreUrls: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreRegExpLiterals: true
    }],
    "id-length": ["error", {min: 3, exceptions: ["i","n","c","x","y","z","e","it","id","cb"]}],
    "id-denylist": "off",
    "eol-last": ["error", "always"],
    "consistent-this": ["error", "self"],
    "computed-property-spacing": ["error", "never"],
    "func-call-spacing": ["error", "never"],
    "func-name-matching": "error",
    "func-names": "off",
    "func-style": ["error", "expression"],
    "function-call-argument-newline": ["error", "consistent"],
    "function-paren-newline": ["error", "consistent"],
    "id-match": "off",
    "implicit-arrow-linebreak": ["off", "below"],
    "indent": ["error", 2],
    "jsx-quotes": ["error", "prefer-double"],
    "key-spacing": ["error", { "align": "value" }],
    "keyword-spacing": ["error", { before: true, after: true }],
    "line-comment-position": "off",
    "linebreak-style": ["error", "unix"],
    "lines-around-comment": ["error", { beforeBlockComment: true }],
    "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
    "max-depth": ["error", 3],
    "max-lines": "off",
    "max-lines-per-function": ["error", { max: 25, skipBlankLines: true, skipComments: true }],
    "max-nested-callbacks": ["error", 4],
    "max-params": ["error", 3],
    "max-statements": ["error", 10],
    "multiline-comment-style": "off",
    "multiline-ternary": "off",
    "newline-per-chained-call": "off",
    "comma-style": ["error", "last"],
    "comma-spacing": ["error", { before: false, after: true }],
    "comma-dangle": ["error", "always-multiline"],
    "capitalized-comments": "off",
    "camelcase": "error",
    "brace-style": ["error", "stroustrup", { allowSingleLine: true }],
    "block-spacing": ["error", "always"],
    "array-element-newline": ["off"],
    "array-bracket-spacing": ["error", "always", { "singleValue": false, objectsInArrays: false, arraysInArrays: false }],
    "array-bracket-newline": ["off"],
    "object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
    "object-curly-spacing": ["error", "always", {arraysInObjects: false, objectsInObjects: false}],
    "object-curly-newline": ["error", { consistent: true }],
    "one-var": ["error", "never"],
    "padded-blocks": ["error", "never"],
    "nonblock-statement-body-position": "off",
  }
}